(let ((bg "#dddddd")
      (red "#cc6666")
      (yellow "#f0c674")
      (green "#b5bd68"))
  (set-face-attribute 'fringe nil :background bg)
  (set-face-attribute 'git-gutter-fr:modified nil :background bg :foreground yellow)
  (set-face-attribute 'git-gutter-fr:added nil :background bg :foreground green)
  (set-face-attribute 'git-gutter-fr:deleted nil :background bg :foreground red)
  (add-to-list 'default-frame-alist `(background-color . ,bg)))
